# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c4b4932d8e13bcdb68e8561100b59c4d4efdcfced16ff33f36d963f445e19c2d60f2e896cfda963ef4d0e1f94dca377fcd96c35023f4d7a336a3820c09a58a1

test:
  secret_key_base: 7e7cd188f6907e546b6032b3ba11d5e87e653d2acba5ddddf8bb8aa2a81c1bd9469ad852b62f70d5ea51873938c3e51c1e1fe9b795acba6a320a15acb8575d16

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
